### ISSUE TITLE
not an issue - swift bindings for tensorflow

### ISSUE THREAD

**Issue by johndpope** [Swift-AI/NeuralNet#3]
I'm looking for collaborators to port tensorflow go over to swift. 
It's been done for go 
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/go

I had a crack at grpc for tensorflow in swift
https://github.com/nubbel/swift-tensorflow/

but will need to re architect this. more info here
https://github.com/nubbel/swift-tensorflow/issues/10

**Comment by collinhundley** [comment]
@johndpope it looks like you're hoping to build a Swift frontend for TensorFlow, right? It sounds like a great project, but I personally wouldn't have the time to contribute right now. Glad to hear more people are taking an interest in ML with Swift!
